name: CI/CD Pipeline

env:
  CI: false

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Add any tests or other steps here

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          cd /home/ec2-user/Lunova/front-end/
          git pull origin main
          npm install
          npm run build
