name: CI/CD Pipeline

env:
  CI: false

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 'node'  # This will use the latest stable Node.js version
        check-latest: true    # This ensures that the cache is checked for the latest version


    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build

    # Add any tests or other steps here

    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        source: "build/"
        target: "/home/ec2-user/Lunova/"
